# Generated by Django 5.2.5 on 2025-08-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='previous_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
