# Generated by Django 5.0.14 on 2025-08-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityimages',
            name='description',
            field=models.TextField(help_text='Enter Description for the image', max_length=999),
        ),
    ]
