# Generated by Django 5.0.14 on 2025-08-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_alter_universityimages_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='description',
            field=models.TextField(help_text='Enter description for your university', max_length=999),
        ),
    ]
