# Generated by Django 5.0.14 on 2025-08-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='description',
            field=models.TextField(help_text='Enter Description for Specific Skill', max_length=999),
        ),
        migrations.AlterField(
            model_name='skillscategory',
            name='description',
            field=models.TextField(help_text='Enter Description For Particular Course', max_length=999),
        ),
    ]
